config/routes.rb
Feedme::Application.routes.draw do
get "feed_entries/index"  
get "feed_entries/refresh"  
get "feed_entries/live"  
get "feeds/index"  
resources :feed_entries
resources :feeds
root :to => 'feeds#index'

end

app/models/feed.rb
class Feed < ActiveRecord::Base
	has_many :feed_entries
end

app/models/feed_entry.rb
require 'uri'
class FeedEntry < ActiveRecord::Base
  belongs_to :feed
  def self.update_from_feed(feed_url, feed_id)
    feed = Feedzirra::Feed.fetch_and_parse(feed_url)
    @feed_url = feed.url
    @fid = feed_id
    add_entries(feed.entries)
  end
  
  def self.update_from_feed_continuously(feed_url, delay_interval = 15.minutes)
    feed = Feedzirra::Feed.fetch_and_parse(feed_url)
    add_entries(feed.entries)
    loop do
      sleep delay_interval
      feed = Feedzirra::Feed.update(feed)
      add_entries(feed.new_entries) if feed.updated?
    end
  end
  
  private
  
  def self.add_entries(entries)
    entries.each do |entry|
      unless exists? :guid => entry.id
      feeds_id = Feed.where(:name => @feed_url)

        uri = URI.parse(entry.url)
        create!(
          :feed_id     => @fid,
          :name         => entry.title.sanitize,
          :summary      => entry.summary,
          :url          => entry.url,
          :published_at => entry.published,
          :guid         => entry.id
        )
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/feed_entries_controller.rb
class FeedEntriesController < ApplicationController
  before_action :set_feed_entry, only: [:show, :edit, :update, :destroy]

  # GET /feed_entries
  # GET /feed_entries.json
  def index
    @feed_entries = FeedEntry.all
  end

  # GET /feed_entries/1
  # GET /feed_entries/1.json
  def show
  end

  def refresh
    @feed_entries = FeedEntry.all(:limit => 40, :order => "published_at desc")
  end

 def live
    @feeds = Feed.all
    @feed_entries = FeedEntry.all(:limit => 40, :order => "published_at desc")
    respond_to do |format|
    @feeds.each do |feed| 
      FeedEntry.update_from_feed(feed.feed_url, feed.id)
    end
      format.html # new.html.erb
      format.json { render json: @feeds }
      format.js
    end
  end

  # GET /feed_entries/new
  def new
    @feed_entry = FeedEntry.new
  end

  # GET /feed_entries/1/edit
  def edit
  end

  # POST /feed_entries
  # POST /feed_entries.json
  def create
    @feed_entry = FeedEntry.new(feed_entry_params)

    respond_to do |format|
      if @feed_entry.save
        format.html { redirect_to @feed_entry, notice: 'Feed entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @feed_entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @feed_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feed_entries/1
  # PATCH/PUT /feed_entries/1.json
  def update
    respond_to do |format|
      if @feed_entry.update(feed_entry_params)
        format.html { redirect_to @feed_entry, notice: 'Feed entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @feed_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feed_entries/1
  # DELETE /feed_entries/1.json
  def destroy
    @feed_entry.destroy
    respond_to do |format|
      format.html { redirect_to feed_entries_url }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed_entry
      @feed_entry = FeedEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_entry_params
      params.require(:feed_entry).permit(:feed_id, :condition, :name, :summary, :url, :published_at, :guid)
    end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

# GET /feeds/new
  # GET /feeds/new.json
  def new
    @feed = Feed.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feed }
      format.js
    end
  end
  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render action: 'show', status: :created, location: @feed }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end
  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:name, :feed_url, :last_modified)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feed_entries_helper.rb
module FeedEntriesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feed_entries/_feed_entry.html.erb
<li id="entry_<%= feed_entry.id %>" rel="feed_<%= feed_entry.feed_id %>"><h1><%= link_to h(feed_entry.name), feed_entry.url %></h1>
<h5><%= Date.parse(feed_entry.published_at.to_s).strftime("%B %e %Y") %></h5>
<h3><%= Feed.where(:id => feed_entry.feed_id).first.name %></h3>
<%= link_to 'Delete', feed_entry, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true %>
  </li>

app/views/feed_entries/_form.html.erb
<%= form_for(@feed_entry) do |f| %>
  <% if @feed_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed_entry.errors.count, "error") %> prohibited this feed_entry from being saved:</h2>

      <ul>
      <% @feed_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :feed_id %><br>
    <%= f.text_field :feed_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br>
    <%= f.datetime_select :published_at %>
  </div>
  <div class="field">
    <%= f.label :guid %><br>
    <%= f.text_field :guid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feed_entries/destroy.js.erb
$('#entry_<%= @feed_entry.id %>').remove();

app/views/feed_entries/edit.html.erb
<h1>Editing feed_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed_entry %> |
<%= link_to 'Back', feed_entries_path %>

app/views/feed_entries/index.html.erb
<h1>Listing feed_entries</h1>

<table>
  <thead>
    <tr>
      <th>Feed</th>
      <th>Name</th>
      <th>Summary</th>
      <th>Url</th>
      <th>Published at</th>
      <th>Guid</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @feed_entries.each do |feed_entry| %>
      <tr>
        <td><%= feed_entry.feed_id %></td>
        <td><%= feed_entry.name %></td>
        <td><%= feed_entry.summary %></td>
        <td><%= feed_entry.url %></td>
        <td><%= feed_entry.published_at %></td>
        <td><%= feed_entry.guid %></td>
        <td><%= link_to 'Show', feed_entry %></td>
        <td><%= link_to 'Edit', edit_feed_entry_path(feed_entry) %></td>
        <td><%= link_to 'Destroy', feed_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed entry', new_feed_entry_path %>

app/views/feed_entries/live.js.erb
$('#feed_entries').append('<%= j render("feed_entry", :feed_entry => @feed_entry) %>');

app/views/feed_entries/new.html.erb
<h1>New feed_entry</h1>

<%= render 'form' %>

<%= link_to 'Back', feed_entries_path %>

app/views/feed_entries/refresh.html.erb
<div id="recent_episodes">
  <h3>Recent Articles</h3>
  <%= link_to "Refresh", :remote => true, :controller => :feed_entries, :action => :live %>
  
   <ul id="feed_entries">
<% @feed_entries.each do |feed_entry| %>
<%= render "feed_entry", :feed_entry => feed_entry %>
<% end %>
  </ul>
</div>

app/views/feed_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Feed:</strong>
  <%= @feed_entry.feed %>
</p>

<p>
  <strong>Name:</strong>
  <%= @feed_entry.name %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @feed_entry.summary %>
</p>

<p>
  <strong>Url:</strong>
  <%= @feed_entry.url %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @feed_entry.published_at %>
</p>

<p>
  <strong>Guid:</strong>
  <%= @feed_entry.guid %>
</p>

<%= link_to 'Edit', edit_feed_entry_path(@feed_entry) %> |
<%= link_to 'Back', feed_entries_path %>

app/views/feeds/_feed.html.erb
<tr id="feed_<%= feed.id %>">
  <td><%= feed.name %></td>
  <td><%= feed.feed_url %></td>
  <td><%= feed.feed_color %></td>
  <td><%= link_to 'Show', feed %></td>
  <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
  <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true %></td>
</tr>

app/views/feeds/_form.html.erb
<%= form_for @feed, :remote => true do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :feed_url %><br>
    <%= f.text_field :feed_url %>
  </div>
  <div class="field">
    <%= f.label :feed_color %><br>
    <%= f.text_field :feed_color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/create.js.erb
$('#new_feed').remove();
$('#new_feed_link').show();
$('#feeds').append('<%= j render("feed", :feed => @feed) %>');

app/views/feeds/destroy.js.erb
$('#feed_<%= @feed.id %>').remove();

app/views/feeds/edit.html.erb
<h1>Editing feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<h1>Listing feeds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Feed url</th>
      <th>Feed Color</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

 <tbody id="feeds">
<% @feeds.each do |feed| %>
<%= render "feed", :feed => feed %>
<% end %>
</tbody>
</table>

<br>


<%= link_to 'New Feed', new_feed_path, :remote => true, :id => "new_feed_link" %>

app/views/feeds/new.html.erb
<h1>New feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/new.js.erb
$('#new_feed_link').hide().after('<%= j render("form") %>');

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @feed.name %>
</p>

<p>
  <strong>Feed url:</strong>
  <%= @feed.feed_url %>
</p>

<p>
  <strong>Last modified:</strong>
  <%= @feed.last_modified %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Feedme">
    <meta name="author" content="Ren Simmons">
    <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">
  <title>Feedme</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">FeedMe</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Feed Settings</a></li>
            <li><a href="/feed_entries/refresh">Live Feed</a></li>
            <li><a href="/feeds/new">+ Add Feed</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    	<div id="page">
    		<div style="padding-top:65px;" class="container">
			<%= yield %>
		</div>
	</div>
</body>
</html>